### PR TITLE
Add remote UDP socket info

### PR DESCRIPTION
**Pull request by andersc**
I made a candidate dealing with UDP server responses as reported here -> 

https://github.com/Ybalrid/kissnet/issues/45

I also made a test for IPv4 and IPv6. 

The 'OLD' API works as before.

/Anders

### CODE REVIEW

**Comment by andersc** [comment]
`sa_len `was a 'BSD' thing ;-)... Will fix the other architectures and re-commit.

**Comment by andersc** [comment]
OK everything passes now on all architectures. However.. I don't like the API passing two parameters. I think it would be better passing a kissnet struct containing the two parameters instead.. But before I go ahead I want to check with you on the over all approach..

**Comment by andersc** [comment]
Cleaned up the interface passing a struct instead.

**Comment by Ybalrid** [comment]
I'm fine with the extra parameter

**Pull request merged**
