### PR TITLE
rework class socket so that one implementation can dynamically handle both ipv4 and ipv6

### LINKED ISSUE #23: ipv6 enabling
I am looking to be able to switch between ipv4 and ipv6 at runtime. Currently it seems that kissnet sticks to ipv4 even when a full ipv6 address is input. This seems to be in part because of the template and following `if constexpr` logic:

```c++
template <protocol sock_proto, ip ipver = ip::v4>
```

What would be the preferred way to make kissnet able to use ipv6 and ipv4 on the fly?

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #23 and https://github.com/kodi-pvr/pvr.hts/issues/483

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]
Seems correct to me

**Comment by ksooo** [comment]
@Ybalrid  mind merging this? I want to release a fixed version of pvr.hts with an official kissnet.hpp, not a patched one.

**Comment by Ybalrid** [comment]
The original idea was to differentiate protocols in the type system itself. However, it's probably not super useful to do so, especially between IPV4 and IPV6.

The idea was to only compile the code that is useful for that specific type of socket in the instantiated template. But looking at the PR, it is clear that this code path is (after that getadddrinfo refactor) clearly shared between the two of them (as they should!)

Change looks good to me. Will merge soon!

**Review by Ybalrid — APPROVED** [review]

**Comment by ksooo** [comment]
Thank you.

**Pull request merged**
