### PR TITLE
Fix socket connect: To determine if a non blocking socket can connect…

### PR DESCRIPTION
**Pull request by ksooo**
…, you need to wait for the select statement first, then check SO_ERROR with getsockopt. That's what we do now.

Affects all hosts with multiple addresses, like a mixture of ipv6 and ipv4 addresses. See comments here: https://github.com/kodi-pvr/pvr.hts/commit/bd99584bbb5f3d1350e8f4c07f70ba0434381969#r45746980

I hope this can be merged soon.

### CODE REVIEW

**Comment by ksooo** [comment]
Hmm, now that the native socket is not created in kissnet::socket ctor anymore, test cases fail.

Calling socket.set_non-blocking() right after socket instance construction now fails because the native socket is not yet created.  But as we've learned creating the right (!) socket is quite difficult (look at the complexity of socket::connect(), can take some time (select() for non-blocking sockets). So, constructing the native socket in kissnet::socket ctor is not really an option.

Any ideas how to deal with this?

**Comment by ksooo** [comment]
Would it be an option to keep the socket ctor unchanged and let it create `sock` for the first working addrinfo and in case connect() gets called to recalculate `sock`using the more sophisticated algorithm to create/connect/select?

**Comment by ksooo** [comment]
> Would it be an option to keep the socket ctor unchanged and let it create sock for the first working addrinfo and in case connect() gets called to recalculate sock using the more sophisticated algorithm to create/connect/select?

 Answering my own question: Yes, I think this is the way to go. Changed the PR accordingly. Tests are green again.

**Comment by ksooo** [comment]
@Ybalrid after some force-pushes yesterday, this PR imo now is ready for merge. So, when you have no objections and find some time, shove it in, please.

**Comment by Ybalrid** [comment]
new `connect` overload is interesting

**Comment by Ybalrid** [comment]
kay, looking good

**Pull request merged**
